import type { DiscordMessagePayload } from '../discord/api'
import type { BuildRow, SquadRow } from '../db'
import emojiMapData from '../discord/emoji-map.json'

/** Same blue used for both board section kinds — this bot only ever posts board-section messages
 *  and command followups, no branding need for more than one accent color yet. */
const BOARD_EMBED_COLOR = 0x3ea6ff

interface EmojiRef {
  name: string
  id: string
}

/** Bot-owned Discord "application emojis" (usable in any guild the bot is in, don't consume a
 *  guild's own emoji slots), keyed by profession name / elite-spec id — same key shapes as
 *  `data/game-data/tango-icons.json`, which is where the source art comes from. Generated by
 *  `scripts/register-emojis.ts` (`npm run register-emojis`, one-time setup + re-run whenever a
 *  new elite spec ships); this file starts out as the empty `{"professions":{},"specializations":{}}`
 *  placeholder committed alongside this code so the build doesn't depend on that script having run
 *  yet. A profession/spec missing from the map (not yet uploaded) just renders with no emoji. */
const EMOJI_MAP = emojiMapData as { professions: Record<string, EmojiRef>; specializations: Record<string, EmojiRef> }

/** `<:name:id>` for a build's elite spec if it has one and it's in the map, else the plain
 *  profession's, else no emoji at all — trailing space included so callers can just concatenate. */
function buildEmojiPrefix(profession: string, specializationId: number | null): string {
  const ref = (specializationId !== null ? EMOJI_MAP.specializations[String(specializationId)] : undefined) ?? EMOJI_MAP.professions[profession]
  return ref ? `<:${ref.name}:${ref.id}> ` : ''
}

/** Renders one profession's board section — the message `/buildBoardSetup`/`/buildBoardRebuild`
 *  create and every `/buildAdd`/`/buildEdit`/`/buildRemove`/`/buildMove` re-PATCHes in place.
 *  Builds are numbered by their `sort_order` position so `/buildMove [Build Name] [position]`'s
 *  numeric argument reads directly off what's displayed. */
export function renderBuildSection(profession: string, builds: BuildRow[]): DiscordMessagePayload {
  const description =
    builds.length === 0
      ? '*(no builds yet — add one with `/buildAdd`)*'
      : builds
          .map((b, i) => `${i + 1}. ${buildEmojiPrefix(b.profession, b.specialization_id)}**${escapeMarkdown(b.name)}**`)
          .join('\n')

  return {
    embeds: [{ title: profession, description, color: BOARD_EMBED_COLOR }]
  }
}

/** Renders the single squad-board message — squads have no per-category sections (see
 *  `SQUAD_BOARD_CATEGORY`'s doc comment), just one add-ordered list. */
export function renderSquadSection(squads: SquadRow[]): DiscordMessagePayload {
  const description =
    squads.length === 0
      ? '*(no squads yet — add one with `/squadAdd`)*'
      : squads.map((s, i) => `${i + 1}. **${escapeMarkdown(s.name)}**`).join('\n')

  return {
    embeds: [{ title: 'Squads', description, color: BOARD_EMBED_COLOR }]
  }
}

/** Discord markdown treats `*_~\`|` as formatting characters — escape them in user-supplied build/
 *  squad names so e.g. a build literally named "Power * Precision" doesn't render as italics.
 *  Exported for `discord/commands/builds.ts`/`squads.ts`'s pending-approval card descriptions,
 *  which quote the same user-supplied names outside a board section. */
export function escapeMarkdown(text: string): string {
  return text.replace(/[*_~`|\\]/g, (ch) => `\\${ch}`)
}
